# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    image: mongo
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGODB_LOCAL_URI: mongodb://root:password123@localhost:6000
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db

  mongo-expresss:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://root:password123@mongo:27017/

volumes:
  mongodb:
